an:
  frontpage: 52
  help docs: 8
  main: 88
  main_1_0: 29
ar:
  frontpage: 52
  help docs: 7
  main: 49
  main_1_0: 16
be-BY:
  frontpage: 58
  help docs: 10
  main: 96
  main_1_0: 32
bg-BG:
  frontpage: 9
  help docs: 2
  main: 41
  main_1_0: 20
ca:
  frontpage: 49
  help docs: 7
  main: 75
  main_1_0: 28
cmn:
  frontpage: 1
  help docs: 1
  main: 30
  main_1_0: 12
cs:
  frontpage: 76
  help docs: 43
  main: 80
  main_1_0: 28
da:
  frontpage: 52
  help docs: 9
  main: 88
  main_1_0: 33
de:
  frontpage: 58
  help docs: 45
  main: 96
  main_1_0: 34
el:
  frontpage: 78
  help docs: 42
  main: 96
  main_1_0: 32
en-BE:
  frontpage: 0
  help docs: 0
  main: 0
  main_1_0: 0
en-NL:
  frontpage: 0
  help docs: 0
  main: 0
  main_1_0: 0
eo:
  frontpage: 52
  help docs: 8
  main: 86
  main_1_0: 29
es:
  frontpage: 100
  help docs: 80
  main: 100
  main_1_0: 100
fa-IR:
  frontpage: 52
  help docs: 1
  main: 13
  main_1_0: 1
fi:
  frontpage: 0
  help docs: 0
  main: 6
  main_1_0: 0
fr:
  frontpage: 58
  help docs: 29
  main: 98
  main_1_0: 38
ga-IE:
  frontpage: 66
  help docs: 9
  main: 61
  main_1_0: 94
gl:
  frontpage: 29
  help docs: 8
  main: 69
  main_1_0: 21
he:
  frontpage: 53
  help docs: 8
  main: 64
  main_1_0: 19
hi:
  frontpage: 0
  help docs: 0
  main: 1
  main_1_0: 0
hr:
  frontpage: 100
  help docs: 14
  main: 46
  main_1_0: 10
hu:
  frontpage: 63
  help docs: 74
  main: 96
  main_1_0: 41
id:
  frontpage: 29
  help docs: 2
  main: 54
  main_1_0: 24
it:
  frontpage: 60
  help docs: 11
  main: 90
  main_1_0: 51
it-CH:
  frontpage: 0
  help docs: 0
  main: 0
  main_1_0: 0
it-IT: {}
ja:
  frontpage: 44
  help docs: 4
  main: 62
  main_1_0: 25
km:
  frontpage: 7
  help docs: 2
  main: 49
  main_1_0: 21
ko:
  frontpage: 52
  help docs: 3
  main: 56
  main_1_0: 22
lt:
  frontpage: 18
  help docs: 7
  main: 5
  main_1_0: 25
lv:
  frontpage: 0
  help docs: 0
  main: 0
  main_1_0: 0
mi:
  frontpage: 1
  help docs: 0
  main: 4
  main_1_0: 5
mk:
  frontpage: 52
  help docs: 3
  main: 54
  main_1_0: 19
ml:
  frontpage: 9
  help docs: 3
  main: 52
  main_1_0: 22
ml-IN:
  frontpage: 0
  help docs: 0
  main: 0
  main_1_0: 0
nl: {}
nl-NL:
  frontpage: 100
  help docs: 47
  main: 94
  main_1_0: 44
pl:
  frontpage: 100
  help docs: 56
  main: 59
  main_1_0: 100
pt-BR:
  frontpage: 100
  help docs: 100
  main: 100
  main_1_0: 100
pt-PT:
  frontpage: 16
  help docs: 0
  main: 9
  main_1_0: 0
ro:
  frontpage: 100
  help docs: 53
  main: 99
  main_1_0: 33
ru:
  frontpage: 58
  help docs: 8
  main: 63
  main_1_0: 20
sk:
  frontpage: 52
  help docs: 8
  main: 88
  main_1_0: 29
sl:
  frontpage: 58
  help docs: 10
  main: 91
  main_1_0: 31
sr:
  frontpage: 58
  help docs: 11
  main: 96
  main_1_0: 32
sr-RS:
  frontpage: 58
  help docs: 10
  main: 94
  main_1_0: 31
sv:
  frontpage: 52
  help docs: 8
  main: 88
  main_1_0: 29
te:
  frontpage: 15
  help docs: 2
  main: 28
  main_1_0: 13
tr:
  frontpage: 52
  help docs: 8
  main: 88
  main_1_0: 29
uk:
  frontpage: 64
  help docs: 8
  main: 75
  main_1_0: 27
ur:
  frontpage: 0
  help docs: 0
  main: 0
  main_1_0: 0
ur-PK:
  frontpage: 0
  help docs: 0
  main: 0
  main_1_0: 0
vi:
  frontpage: 7
  help docs: 2
  main: 44
  main_1_0: 20
zh-TW:
  frontpage: 64
  help docs: 45
  main: 99
  main_1_0: 32
