an:
  frontpage: 52
  help docs: 8
  main: 88
  main_1_0: 32
ar:
  frontpage: 52
  help docs: 7
  main: 49
  main_1_0: 18
be-BY:
  frontpage: 58
  help docs: 10
  main: 96
  main_1_0: 35
bg-BG:
  frontpage: 9
  help docs: 2
  main: 41
  main_1_0: 20
ca:
  frontpage: 49
  help docs: 7
  main: 75
  main_1_0: 30
cmn:
  frontpage: 1
  help docs: 1
  main: 30
  main_1_0: 13
cs:
  frontpage: 76
  help docs: 43
  main: 80
  main_1_0: 31
da:
  frontpage: 52
  help docs: 8
  main: 88
  main_1_0: 32
de:
  frontpage: 58
  help docs: 45
  main: 96
  main_1_0: 36
el:
  frontpage: 78
  help docs: 42
  main: 96
  main_1_0: 36
eo:
  frontpage: 52
  help docs: 8
  main: 86
  main_1_0: 32
es:
  frontpage: 95
  help docs: 74
  main: 99
  main_1_0: 36
fa-IR:
  frontpage: 52
  help docs: 1
  main: 13
  main_1_0: 1
fi:
  frontpage: 0
  help docs: 0
  main: 6
  main_1_0: 0
fr:
  frontpage: 58
  help docs: 29
  main: 98
  main_1_0: 36
ga-IE:
  frontpage: 66
  help docs: 7
  main: 57
  main_1_0: 25
gl:
  frontpage: 29
  help docs: 8
  main: 69
  main_1_0: 24
he:
  frontpage: 53
  help docs: 8
  main: 64
  main_1_0: 22
hi:
  frontpage: 0
  help docs: 0
  main: 1
  main_1_0: 0
hr:
  frontpage: 100
  help docs: 14
  main: 46
  main_1_0: 12
hu:
  frontpage: 61
  help docs: 72
  main: 96
  main_1_0: 36
id:
  frontpage: 29
  help docs: 2
  main: 54
  main_1_0: 25
it:
  frontpage: 60
  help docs: 8
  main: 89
  main_1_0: 32
it-CH:
  frontpage: 0
  help docs: 0
  main: 0
  main_1_0: 0
ja:
  frontpage: 44
  help docs: 4
  main: 62
  main_1_0: 27
km:
  frontpage: 7
  help docs: 2
  main: 49
  main_1_0: 22
ko:
  frontpage: 52
  help docs: 3
  main: 56
  main_1_0: 23
lv:
  frontpage: 0
  help docs: 0
  main: 0
  main_1_0: 0
mi:
  frontpage: 1
  help docs: 0
  main: 4
  main_1_0: 5
mk:
  frontpage: 52
  help docs: 3
  main: 54
  main_1_0: 21
ml:
  frontpage: 9
  help docs: 3
  main: 52
  main_1_0: 23
ml-IN:
  frontpage: 0
  help docs: 0
  main: 0
  main_1_0: 0
nl-NL:
  frontpage: 58
  help docs: 47
  main: 94
  main_1_0: 36
pl:
  frontpage: 56
  help docs: 1
  main: 18
  main_1_0: 7
pt-BR:
  frontpage: 100
  help docs: 100
  main: 100
  main_1_0: 36
pt-PT:
  frontpage: 16
  help docs: 0
  main: 9
  main_1_0: 0
ro:
  frontpage: 100
  help docs: 53
  main: 99
  main_1_0: 36
ru:
  frontpage: 58
  help docs: 8
  main: 63
  main_1_0: 22
sk:
  frontpage: 52
  help docs: 8
  main: 88
  main_1_0: 32
sl:
  frontpage: 58
  help docs: 10
  main: 91
  main_1_0: 35
sr:
  frontpage: 58
  help docs: 10
  main: 94
  main_1_0: 35
sr-RS:
  frontpage: 58
  help docs: 10
  main: 94
  main_1_0: 35
sv:
  frontpage: 52
  help docs: 8
  main: 88
  main_1_0: 32
te:
  frontpage: 15
  help docs: 2
  main: 28
  main_1_0: 14
tr:
  frontpage: 52
  help docs: 8
  main: 88
  main_1_0: 32
uk:
  frontpage: 64
  help docs: 8
  main: 75
  main_1_0: 31
ur:
  frontpage: 0
  help docs: 0
  main: 0
  main_1_0: 0
ur-PK:
  frontpage: 0
  help docs: 0
  main: 0
  main_1_0: 0
vi:
  frontpage: 7
  help docs: 2
  main: 44
  main_1_0: 21
zh-TW:
  frontpage: 64
  help docs: 45
  main: 99
  main_1_0: 36
