an:
  frontpage: 52
  help docs: 8
  main: 88
  main_1_0: 28
ar:
  frontpage: 52
  help docs: 7
  main: 49
  main_1_0: 15
be-BY:
  frontpage: 58
  help docs: 10
  main: 96
  main_1_0: 30
bg-BG:
  frontpage: 9
  help docs: 2
  main: 41
  main_1_0: 19
ca:
  frontpage: 49
  help docs: 7
  main: 74
  main_1_0: 26
cmn:
  frontpage: 1
  help docs: 1
  main: 30
  main_1_0: 12
cs:
  frontpage: 76
  help docs: 44
  main: 79
  main_1_0: 68
da:
  frontpage: 52
  help docs: 11
  main: 88
  main_1_0: 41
de:
  frontpage: 100
  help docs: 55
  main: 100
  main_1_0: 100
el:
  frontpage: 78
  help docs: 42
  main: 95
  main_1_0: 31
en-BE:
  frontpage: 0
  help docs: 0
  main: 0
  main_1_0: 0
en-NL:
  frontpage: 0
  help docs: 0
  main: 0
  main_1_0: 0
eo:
  frontpage: 52
  help docs: 8
  main: 86
  main_1_0: 27
es:
  frontpage: 100
  help docs: 85
  main: 99
  main_1_0: 93
fa-IR:
  frontpage: 60
  help docs: 41
  main: 14
  main_1_0: 2
fi:
  frontpage: 0
  help docs: 0
  main: 6
  main_1_0: 0
fr:
  frontpage: 58
  help docs: 29
  main: 97
  main_1_0: 36
ga-IE:
  frontpage: 69
  help docs: 9
  main: 60
  main_1_0: 89
gl:
  frontpage: 29
  help docs: 8
  main: 68
  main_1_0: 20
he:
  frontpage: 55
  help docs: 8
  main: 64
  main_1_0: 18
he-IL: {}
hi:
  frontpage: 0
  help docs: 0
  main: 1
  main_1_0: 0
hr:
  frontpage: 100
  help docs: 14
  main: 46
  main_1_0: 9
hu:
  frontpage: 63
  help docs: 74
  main: 96
  main_1_0: 39
id:
  frontpage: 29
  help docs: 2
  main: 53
  main_1_0: 22
it:
  frontpage: 60
  help docs: 41
  main: 89
  main_1_0: 86
it-CH:
  frontpage: 0
  help docs: 0
  main: 0
  main_1_0: 0
it-IT: {}
ja:
  frontpage: 44
  help docs: 4
  main: 62
  main_1_0: 24
km:
  frontpage: 7
  help docs: 2
  main: 49
  main_1_0: 20
ko:
  frontpage: 52
  help docs: 3
  main: 56
  main_1_0: 21
lt:
  frontpage: 23
  help docs: 9
  main: 9
  main_1_0: 50
lv:
  frontpage: 0
  help docs: 0
  main: 0
  main_1_0: 0
mi:
  frontpage: 1
  help docs: 0
  main: 4
  main_1_0: 5
mk:
  frontpage: 52
  help docs: 3
  main: 54
  main_1_0: 18
ml:
  frontpage: 9
  help docs: 3
  main: 52
  main_1_0: 20
ml-IN:
  frontpage: 0
  help docs: 0
  main: 0
  main_1_0: 0
nl: {}
nl-NL:
  frontpage: 100
  help docs: 47
  main: 93
  main_1_0: 41
pl:
  frontpage: 100
  help docs: 56
  main: 59
  main_1_0: 92
pt-BR:
  frontpage: 100
  help docs: 100
  main: 100
  main_1_0: 100
pt-PT:
  frontpage: 16
  help docs: 0
  main: 9
  main_1_0: 0
ro:
  frontpage: 100
  help docs: 53
  main: 98
  main_1_0: 31
ru:
  frontpage: 60
  help docs: 10
  main: 64
  main_1_0: 29
sk:
  frontpage: 52
  help docs: 8
  main: 88
  main_1_0: 28
sl:
  frontpage: 58
  help docs: 10
  main: 91
  main_1_0: 36
sr:
  frontpage: 58
  help docs: 11
  main: 95
  main_1_0: 30
sr-RS:
  frontpage: 58
  help docs: 10
  main: 94
  main_1_0: 30
sv:
  frontpage: 52
  help docs: 8
  main: 87
  main_1_0: 27
te:
  frontpage: 15
  help docs: 2
  main: 28
  main_1_0: 13
tr:
  frontpage: 52
  help docs: 10
  main: 88
  main_1_0: 39
uk:
  frontpage: 64
  help docs: 8
  main: 75
  main_1_0: 26
ur:
  frontpage: 0
  help docs: 0
  main: 0
  main_1_0: 0
ur-PK:
  frontpage: 0
  help docs: 0
  main: 0
  main_1_0: 0
vi:
  frontpage: 7
  help docs: 2
  main: 44
  main_1_0: 19
zh-TW:
  frontpage: 100
  help docs: 46
  main: 100
  main_1_0: 99
